"""
网站仓库 PR 提交器
"""
import logging
import os
import subprocess
import tempfile
from pathlib import Path
from typing import List

logger = logging.getLogger(__name__)


class WebsitePR:
    """向网站仓库提交报告的 PR 创建器"""
    
    def __init__(self):
        self.website_repo = "https://github.com/xiexiuqi/xiexiuqi.github.io.git"
        self.token = os.environ.get('WEBSITE_REPO_TOKEN')
        
    def create_pr(self, report_paths: List[str]) -> str:
        """
        创建 PR 提交报告到网站仓库
        
        Args:
            report_paths: 报告文件路径列表
            
        Returns:
            PR URL
        """
        if not self.token:
            logger.warning("WEBSITE_REPO_TOKEN not set, skipping PR creation")
            # 本地模式：直接复制到本地目录
            return self._copy_local(report_paths)
        
        try:
            # 创建临时目录
            with tempfile.TemporaryDirectory() as tmpdir:
                repo_dir = Path(tmpdir) / "website"
                
                # 克隆网站仓库
                logger.info(f"Cloning website repo to {repo_dir}")
                clone_url = self.website_repo.replace(
                    "https://github.com/",
                    f"https://{self.token}@github.com/"
                )
                
                result = subprocess.run(
                    ["git", "clone", clone_url, str(repo_dir)],
                    capture_output=True,
                    text=True,
                    check=True
                )
                
                # 创建新分支
                branch_name = f"auto/insights-{os.environ.get('GITHUB_RUN_ID', 'local')}"
                subprocess.run(
                    ["git", "checkout", "-b", branch_name],
                    cwd=repo_dir,
                    check=True
                )
                
                # 复制报告文件
                for report_path in report_paths:
                    self._copy_report_to_repo(report_path, repo_dir)
                
                # 提交更改
                subprocess.run(
                    ["git", "config", "user.email", "insights@bot.local"],
                    cwd=repo_dir,
                    check=True
                )
                subprocess.run(
                    ["git", "config", "user.name", "Linux Performance Insights"],
                    cwd=repo_dir,
                    check=True
                )
                
                subprocess.run(
                    ["git", "add", "."],
                    cwd=repo_dir,
                    check=True
                )
                
                result = subprocess.run(
                    ["git", "commit", "-m", 
                     f"📊 Auto-generated performance reports\n\nGenerated by Linux Performance Insights"],
                    cwd=repo_dir,
                    capture_output=True,
                    text=True
                )
                
                if result.returncode != 0:
                    logger.warning(f"Git commit may have failed: {result.stderr}")
                    # 如果没有变更，返回成功
                    if "nothing to commit" in result.stderr:
                        logger.info("No changes to commit")
                        return "No changes"
                
                # 推送分支
                subprocess.run(
                    ["git", "push", "origin", branch_name],
                    cwd=repo_dir,
                    check=True
                )
                
                logger.info(f"Branch pushed: {branch_name}")
                
                # 返回 PR URL（实际创建 PR 需要通过 GitHub API）
                pr_url = f"https://github.com/xiexiuqi/xiexiuqi.github.io/pulls"
                return pr_url
                
        except Exception as e:
            logger.error(f"Failed to create PR: {e}")
            # 本地模式回退
            return self._copy_local(report_paths)
    
    def _copy_report_to_repo(self, report_path: str, repo_dir: Path):
        """复制报告到仓库目录"""
        report_file = Path(report_path)
        
        # 根据报告类型确定目标目录
        if "daily" in report_path:
            target_dir = repo_dir / "daily"
        elif "weekly" in report_path:
            target_dir = repo_dir / "reports" / "weekly"
        elif "kernel-versions" in report_path:
            target_dir = repo_dir / "reports"
        else:
            target_dir = repo_dir / "reports"
        
        target_dir.mkdir(parents=True, exist_ok=True)
        
        # 复制文件
        target_file = target_dir / report_file.name
        import shutil
        shutil.copy2(report_path, target_file)
        
        logger.info(f"Copied {report_path} -> {target_file}")
    
    def _copy_local(self, report_paths: List[str]) -> str:
        """本地模式：复制到本地目录"""
        logger.info("Using local copy mode")
        
        # 本地开发时，复制到 ../xiexiuqi.github.io/
        local_repo = Path("../xiexiuqi.github.io")
        
        if not local_repo.exists():
            logger.warning(f"Local repo not found: {local_repo}")
            return "Local repo not found"
        
        for report_path in report_paths:
            self._copy_report_to_repo(report_path, local_repo)
        
        logger.info(f"Reports copied to local repo: {local_repo}")
        return f"Local: {local_repo}"
